### Login with default user credentials
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "annouck.lancaster@vinci.be",
  "password": "a"
}

> {%
  client.global.set("token", response.body.token);
%}

### Register john
POST {{baseUrl}}/auth/register
Content-Type: application/json
Authorization: {{token}}

{
  "email": "zeub.humide@student.vinci.be",
  "password": "a",
  "lastname": "zeub",
  "firstname": "humide",
  "phone": "123456789",
  "role": "E"
}

> {%
client.global.set("token", response.body.token);
%}

###
PUT {{baseUrl}}/auth/4
Content-Type: application/json
Authorization : {{token}}



{
  "email": "annouck.lancaster@vinci.be",
  "lastname": "Lancaster",
  "firstname": "Annouck",
  "phone": "444444444",
  "role": "E"
}