### Login with default user credentials
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "resul.ramadani@student.vinci.be",
  "password": "a"
}

### Register john
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "admin.admin@vinci.be",
  "password": "a",
  "name": "admin",
  "firstname": "admin",
  "phone": "123456789",
  "confirmPassword": "a",
  "role": "A"
}

> {%
client.global.set("token", response.body.token);
%}


### Get
GET {{baseUrl}}/auth/user
Authorization: {{token}}

###get stage
GET {{baseUrl}}/auth/stage
Authorization: {{token}}

###get contacts
GET {{baseUrl}}/auth/contact
Authorization: {{token}}

