### Login with default user credentials
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "Carole.skile@student.vinci.be",
  "password": "a"
}

> {%
  client.global.set("token", response.body.token);
%}

### Get all companies
GET {{baseUrl}}/entreprise
Content-Type: application/json
Authorization: {{token}}

### add a company
POST {{baseUrl}}/entreprise
Content-Type: application/json
Authorization: {{token}}

{

  "nom": "Vinci",
  "appellation": "Construction",
  "adresse": "rue de la loi",
  "city": "Bruxelles",
  "numTel": "0487654321",
  "email": "t@gmail.com",
  "blackListed": false,
  "motivation": "none",
  "version": "1"
}
