### Login with default user credentials
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "nadir.ahdid@student.vinci.be",
  "password": "a"
}

> {%
  client.global.set("token", response.body.token);
%}

### Insert a new contact
POST {{baseUrl}}/contacts/insert
Authorization: {{token}}
Content-Type: application/json

{
  "entreprise": {
    "id": 1,
    "nom": "Assyst Europe",
    "appellation": "",
    "adresse": "Avenue du Japon, 1/B9",
    "numTel": "02.609.25.00",
    "email": null,
    "blackListed": false,
    "city": null,
    "motivation_blacklist": null
  },
  "utilisateur": {
    "id": 10,
    "email": "nadir.ahdid@student.vinci.be",
    "lastname": "nadir",
    "firstname": "ahdid",
    "phone": "0485367792",
    "registrationDate": "23-03-24 11:00:00",
    "role": "E",
    "hasInternship": false,
    "version": 1,
    "year": {
      "id": 1,
      "annee": "2023-2024",
      "version": 1
    }
  }
}

### Get all contacts
GET {{baseUrl}}/contacts/5
Authorization: {{token}}

### Update a contact
PUT {{baseUrl}}/contacts/update
Authorization: {{token}}
Content-Type: application/json

{
    "id": 12,
    "entreprise": {
      "id": 1,
      "nom": "Assyst Europe",
      "appellation": "",
      "adresse": "Avenue du Japon, 1/B9",
      "numTel": "02.609.25.00",
      "email": null,
      "blackListed": false,
      "city": null,
      "motivation_blacklist": null
    },
    "utilisateur": {
      "id": 10,
      "email": "nadir.ahdid@student.vinci.be",
      "lastname": "nadir",
      "firstname": "ahdid",
      "phone": "0485367792",
      "registrationDate": "23-03-24 11:00:00",
      "role": "E",
      "hasInternship": false,
      "version": 1,
      "year": {
        "id": 1,
        "annee": "2023-2024",
        "version": 1
      }
    },
  "etatContact": "accepté",
  "raisonRefus": null,
  "lieuxRencontre": null,
  "version": 1
}

### Get all contacts with idCompany
GET {{baseUrl}}/contacts/1/company
Authorization: {{token}}
Content-Type: application/json
