### Login with default user credentials
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "annouck.lancaster@vinci.be",
  "password": "a"
}

> {%
    client.global.set("token", response.body.token);
%}

### Get all users
GET {{baseUrl}}/auth
Authorization: {{token}}

### Get user by id
GET {{baseUrl}}/users
Authorization: {{token}}

### verify user's old password
POST {{baseUrl}}/users/4/verify
Authorization: {{token}}
Content-Type: application/json

{
  "Password": "a"
}

### put
PUT {{baseUrl}}/users/4
Authorization: {{token}}
Content-Type: application/json

{
  "id": 4,
  "phone": "0474747474"
}