### Login with default user credentials
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "annouck.lancaster@vinci.be",
  "password": "a"
}

> {%
    client.global.set("token", response.body.token);
%}

### Get all users
GET {{baseUrl}}/auth
Authorization: {{token}}

### Get user by id
GET {{baseUrl}}/users
Authorization: {{token}}

###
PUT {{baseUrl}}/users/4
Content-Type: application/json
Authorization : {{token}}


{
  "email": "annouck.lancaster@vinci.be",
  "lastname": "Lancaster",
  "firstname": "Annouck",
  "phone": "444444444",
  "role": "E",
  "password": "aaaaaaaa"
}